services:
  postgres:
    build:
      context: .
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION:-16}
        DB_NAME: ${DB_NAME:-openimis}
        DB_USER: ${DB_USER:-openimis_user}
        INIT_SCRIPT: ${INIT_SCRIPT:-fullDemoDatabase.sql}
    container_name: ${CONTAINER_NAME:-openimis_postgresql}
    environment:
      POSTGRES_DB: ${DB_NAME:-openimis}
      POSTGRES_USER: ${DB_USER:-openimis_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-SuperSafePassword}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./${INIT_SCRIPT:-fullDemoDatabase.sql}:/${INIT_SCRIPT:-fullDemoDatabase.sql}:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-openimis_user} -d ${DB_NAME:-openimis}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
