version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: openimis_postgresql
    environment:
      POSTGRES_DB: openimis
      POSTGRES_USER: openimis_user
      POSTGRES_PASSWORD: SuperSafePassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./fullDemoDatabase.sql:/fullDemoDatabase.sql:ro
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    restart: unless-stopped

volumes:
  pgdata:

